In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

uploaded = files.upload()

Saving customers.csv to customers.csv
Saving order_items.csv to order_items.csv
Saving orders.csv to orders.csv
Saving products.csv to products.csv
Saving reviews.csv to reviews.csv

In [3]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
reviews = pd.read_csv("reviews.csv")

In [ ]:
customers.head()

,customer_id,name,email,phone,city,province,registration_date,gender,age_group
0,CUST0001,Andi Rahmawati,andirahmawati229@yahoo.com,8.211820e+10,Semarang,Jawa Tengah,2022-04-22,Male,25-34
1,CUST0002,Sari Sembiring,sarisembiring226@gmail.com,8.579403e+10,Semarang,Jawa Tengah,2022-11-21,Female,18-24
2,CUST0003,Bella Aprilia,bellaaprilia271@gmail.com,8.127816e+10,Tangerang,Banten,2024-03-28,Female,18-24
3,CUST0004,Shinta Hartono,shintahartono82@outlook.com,8.221648e+10,Semarang,Jawa Tengah,2024-10-04,Female,25-34
4,CUST0005,Maulana Hidayat,maulanahidayat651@gmail.com,8.218328e+10,Bekasi,Jawa Barat,2021-04-25,Male,18-24

In [4]:
products.head()

,product_id,name,category,sub_category,price_idr,stock,brand,material,avg_rating
0,PRD001,Dress Bodycon Pesona Indo,dress,Atasan Wanita,599000,0,Pesona Indo,Linen,5.0
1,PRD002,Kaos Oversize BajuKita,T-Shirt,Atasan Pria,329000,239,BajuKita,Cotton 100%,3.7
2,PRD003,Dress Maxi Polos Senja Wear,dress,Atasan Wanita,349000,80,Senja Wear,Cotton-Polyester,4.7
3,PRD004,Ikat Pinggang Kulit Cendana Co,Accessories,Aksesoris,199000,309,Cendana Co,Denim,4.6
4,PRD005,Dress Bodycon Senja Wear,dress,Atasan Wanita,599000,192,Senja Wear,Polyester,3.5

In [5]:
orders.head()

,order_id,customer_id,order_date,total_amount_idr,shipping_city,shipping_province,shipping_cost_idr,payment_method,order_status,promo_code,discount_amount_idr,courier
0,ORD000001,CUST0474,2023-03-23,1951591,Banjarmasin,Kalimantan Selatan,32066,Transfer Bank,shipped,WEEKEND25,44409.0,JNE
1,ORD000002,CUST0478,2025-02-26,507000,Palembang,Sumatera Selatan,33769,Kartu Kredit,delivered,NaN,NaN,JNE
2,ORD000003,CUST0306,2022-07-13,199000,Tangerang,Banten,12060,Transfer Bank,delivered,NaN,NaN,SiCepat
3,ORD000004,CUST0777,2024-11-26,119000,Medan,Sumatera Utara,29005,Transfer Bank,cancelled,NaN,NaN,Anteraja
4,ORD000005,CUST0210,2023-07-31,358000,Bandung,Jawa Barat,11192,Kartu Kredit,cancelled,NaN,NaN,JNE

In [6]:
order_items.head()

     item_id   order_id product_id  quantity  unit_price_idr  subtotal_idr
0  ITM000001  ORD000001     PRD070         1          349000        349000
1  ITM000002  ORD000001     PRD001         2          599000       1198000
2  ITM000003  ORD000001     PRD148         1          449000        449000
3  ITM000004  ORD000002     PRD086         1          329000        329000
4  ITM000005  ORD000002     PRD258         1          129000        129000

In [7]:
reviews.head()

,review_id,order_id,product_id,customer_id,rating,review_text,review_date,helpful_count
0,REV00001,ORD000131,PRD269,CUST0714,3,"Bahan premium, jahitan kuat.",2024-02-16,0
1,REV00002,ORD001162,PRD105,CUST0586,2,"Bagus banget, packaging juga aman.",2025-01-24,0
2,REV00003,ORD001172,PRD053,CUST0164,5,"Modelnya keren, fit di badan.",2024-09-18,18
3,REV00004,ORD002879,PRD265,CUST0179,4,Kualitas oke untuk harga segini.,2024-03-16,0
4,REV00005,ORD001303,PRD252,CUST0606,3,"Produk sampai dengan cepat, sesuai ekspektasi.",2024-01-26,46

In [8]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Reviews:", reviews.shape)

Customers: (800, 9)
Products: (300, 9)
Orders: (3000, 12)
Order Items: (4986, 6)
Reviews: (1500, 8)

In [9]:
print(customers.columns.tolist())
print(products.columns.tolist())
print(orders.columns.tolist())
print(order_items.columns.tolist())
print(reviews.columns.tolist())

['customer_id', 'name', 'email', 'phone', 'city', 'province', 'registration_date', 'gender', 'age_group']
['product_id', 'name', 'category', 'sub_category', 'price_idr', 'stock', 'brand', 'material', 'avg_rating']
['order_id', 'customer_id', 'order_date', 'total_amount_idr', 'shipping_city', 'shipping_province', 'shipping_cost_idr', 'payment_method', 'order_status', 'promo_code', 'discount_amount_idr', 'courier']
['item_id', 'order_id', 'product_id', 'quantity', 'unit_price_idr', 'subtotal_idr']
['review_id', 'order_id', 'product_id', 'customer_id', 'rating', 'review_text', 'review_date', 'helpful_count']

In [10]:
customers.info()
products.info()
orders.info()
order_items.info()
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        800 non-null    object
 1   name               800 non-null    object
 2   email              800 non-null    object
 3   phone              760 non-null    float64
 4   city               800 non-null    object
 5   province           800 non-null    object
 6   registration_date  800 non-null    object
 7   gender             800 non-null    object
 8   age_group          800 non-null    object
dtypes: float64(1), object(8)
memory usage: 56.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    300 non-null    object
 1   name          300 non-null    object
 2   category      300 non-null    object
 3   sub_category  300 non-null    object
 4   price_idr     300 non-null    int64
 5   stock         300 non-null    int64
 6   brand         300 non-null    object
 7   material      291 non-null    object
 8   avg_rating    300 non-null    float64
dtypes: float64(1), int64(2), object(6)
memory usage: 21.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             3000 non-null   object
 1   customer_id          3000 non-null   object
 2   order_date           3000 non-null   object
 3   total_amount_idr     3000 non-null   int64
 4   shipping_city        3000 non-null   object
 5   shipping_province    3000 non-null   object
 6   shipping_cost_idr    3000 non-null   int64
 7   payment_method       3000 non-null   object
 8   order_status         3000 non-null   object
 9   promo_code           1214 non-null   object
 10  discount_amount_idr  1214 non-null   float64
 11  courier              3000 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 281.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4986 entries, 0 to 4985
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   item_id         4986 non-null   object
 1   order_id        4986 non-null   object
 2   product_id      4986 non-null   object
 3   quantity        4986 non-null   int64
 4   unit_price_idr  4986 non-null   int64
 5   subtotal_idr    4986 non-null   int64
dtypes: int64(3), object(3)
memory usage: 233.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   review_id      1500 non-null   object
 1   order_id       1500 non-null   object
 2   product_id     1500 non-null   object
 3   customer_id    1500 non-null   object
 4   rating         1500 non-null   int64
 5   review_text    1380 non-null   object
 6   review_date    1500 non-null   object
 7   helpful_count  1500 non-null   int64
dtypes: int64(2), object(6)
memory usage: 93.9+ KB

In [11]:
orders.dtypes

order_id                object
customer_id             object
order_date              object
total_amount_idr         int64
shipping_city           object
shipping_province       object
shipping_cost_idr        int64
payment_method          object
order_status            object
promo_code              object
discount_amount_idr    float64
courier                 object
dtype: object

In [12]:
customers.dtypes

customer_id           object
name                  object
email                 object
phone                float64
city                  object
province              object
registration_date     object
gender                object
age_group             object
dtype: object

In [13]:
reviews.dtypes

review_id        object
order_id         object
product_id       object
customer_id      object
rating            int64
review_text      object
review_date      object
helpful_count     int64
dtype: object

In [14]:
#used to convert the date columns from normal text into proper datetime format.
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"],
    errors="coerce"
)

orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

reviews["review_date"] = pd.to_datetime(
    reviews["review_date"],
    errors="coerce"
)

In [15]:
orders.dtypes

order_id                       object
customer_id                    object
order_date             datetime64[ns]
total_amount_idr                int64
shipping_city                  object
shipping_province              object
shipping_cost_idr               int64
payment_method                 object
order_status                   object
promo_code                     object
discount_amount_idr           float64
courier                        object
dtype: object

In [16]:
reviews.dtypes

review_id                object
order_id                 object
product_id               object
customer_id              object
rating                    int64
review_text              object
review_date      datetime64[ns]
helpful_count             int64
dtype: object

In [17]:
print(customers.isnull().sum())
print(products.isnull().sum())
print(orders.isnull().sum())
print(order_items.isnull().sum())
print(reviews.isnull().sum())

customer_id           0
name                  0
email                 0
phone                40
city                  0
province              0
registration_date     0
gender                0
age_group             0
dtype: int64
product_id      0
name            0
category        0
sub_category    0
price_idr       0
stock           0
brand           0
material        9
avg_rating      0
dtype: int64
order_id                  0
customer_id               0
order_date                0
total_amount_idr          0
shipping_city             0
shipping_province         0
shipping_cost_idr         0
payment_method            0
order_status              0
promo_code             1786
discount_amount_idr    1786
courier                   0
dtype: int64
item_id           0
order_id          0
product_id        0
quantity          0
unit_price_idr    0
subtotal_idr      0
dtype: int64
review_id          0
order_id           0
product_id         0
customer_id        0
rating             0
review_text      120
review_date        0
helpful_count      0
dtype: int64

In [18]:
orders["promo_code"] = orders["promo_code"].fillna("No Promo")

In [19]:
orders["discount_amount_idr"] = orders["discount_amount_idr"].fillna(0)

In [20]:
products["material"] = products["material"].fillna("Unknown")

In [21]:
reviews["review_text"] = reviews["review_text"].fillna("No Review Text")

In [22]:
print(customers.isnull().sum())
print(products.isnull().sum())
print(orders.isnull().sum())
print(order_items.isnull().sum())
print(reviews.isnull().sum())

customer_id           0
name                  0
email                 0
phone                40
city                  0
province              0
registration_date     0
gender                0
age_group             0
dtype: int64
product_id      0
name            0
category        0
sub_category    0
price_idr       0
stock           0
brand           0
material        0
avg_rating      0
dtype: int64
order_id               0
customer_id            0
order_date             0
total_amount_idr       0
shipping_city          0
shipping_province      0
shipping_cost_idr      0
payment_method         0
order_status           0
promo_code             0
discount_amount_idr    0
courier                0
dtype: int64
item_id           0
order_id          0
product_id        0
quantity          0
unit_price_idr    0
subtotal_idr      0
dtype: int64
review_id        0
order_id         0
product_id       0
customer_id      0
rating           0
review_text      0
review_date      0
helpful_count    0
dtype: int64

In [23]:
customers["phone"] = customers["phone"].fillna("Not Available")

In [24]:
print(customers.isnull().sum())
print(products.isnull().sum())
print(orders.isnull().sum())
print(order_items.isnull().sum())
print(reviews.isnull().sum())

customer_id          0
name                 0
email                0
phone                0
city                 0
province             0
registration_date    0
gender               0
age_group            0
dtype: int64
product_id      0
name            0
category        0
sub_category    0
price_idr       0
stock           0
brand           0
material        0
avg_rating      0
dtype: int64
order_id               0
customer_id            0
order_date             0
total_amount_idr       0
shipping_city          0
shipping_province      0
shipping_cost_idr      0
payment_method         0
order_status           0
promo_code             0
discount_amount_idr    0
courier                0
dtype: int64
item_id           0
order_id          0
product_id        0
quantity          0
unit_price_idr    0
subtotal_idr      0
dtype: int64
review_id        0
order_id         0
product_id       0
customer_id      0
rating           0
review_text      0
review_date      0
helpful_count    0
dtype: int64

In [25]:
print(customers.duplicated().sum())
print(products.duplicated().sum())
print(orders.duplicated().sum())
print(order_items.duplicated().sum())
print(reviews.duplicated().sum())

0
0
0
0
0

In [26]:
#Check duplicate primary IDs.
customers["customer_id"].duplicated().sum()

np.int64(0)

In [27]:
products["product_id"].duplicated().sum()

np.int64(0)

In [28]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [29]:
order_items["item_id"].duplicated().sum()

np.int64(0)

In [30]:
reviews["review_id"].duplicated().sum()

np.int64(0)

In [31]:
#Check the known duplicate email problem.
customers[
    customers["email"].duplicated(keep=False)
].sort_values("email")

,customer_id,name,email,phone,city,province,registration_date,gender,age_group
44,CUST0045,Bagus Permata,baguspermata248@gmail.com,89667837770.0,Bandung,Jawa Barat,2022-08-26,Male,18-24
320,CUST0321,Teguh Iskandar,baguspermata248@gmail.com,85759876220.0,Makassar,Sulawesi Selatan,2022-04-26,Male,35-44
699,CUST0700,Rina Lestari,rinalestari281@outlook.com,85731584776.0,Banjarmasin,Kalimantan Selatan,2023-03-31,Female,45+
754,CUST0755,Kirana Tarigan,rinalestari281@outlook.com,89538458810.0,Tangerang,Banten,2023-04-22,Female,35-44
187,CUST0188,Wulan Suryadi,wulansuryadi729@yahoo.com,85336729466.0,Padang,Sumatera Barat,2021-06-04,Female,25-34
566,CUST0567,Olivia Lestari,wulansuryadi729@yahoo.com,85204456690.0,Pekanbaru,Riau,2024-09-01,Female,25-34

In [32]:
#You have different tables connected using IDs. We are just checking whether those connections are valid.
len(set(orders["customer_id"]) - set(customers["customer_id"]))
len(set(order_items["order_id"]) - set(orders["order_id"]))
len(set(order_items["product_id"]) - set(products["product_id"]))

0

In [ ]:
#Check numerical columns for impossible values.
customers.describe(include="all")

,customer_id,name,email,phone,city,province,registration_date,gender,age_group
count,800,800,800,800,800,800,800,800,800
unique,800,729,797,761,20,16,NaN,2,4
top,CUST0784,Hadi Fauzi,wulansuryadi729@yahoo.com,Not Available,Manado,Jawa Barat,NaN,Female,25-34
freq,1,3,2,40,49,162,NaN,451,332
mean,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-27 00:45:00,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-02 00:00:00,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-02 12:00:00,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-25 00:00:00,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-10 18:00:00,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-29 00:00:00,NaN,NaN

In [34]:
products.describe()

           price_idr       stock  avg_rating
count     300.000000  300.000000  300.000000
mean   239733.333333  133.940000    4.262333
std    156297.446754  126.568486    0.443173
min     49000.000000    0.000000    3.500000
25%    114000.000000   33.000000    3.900000
50%    199000.000000  106.000000    4.250000
75%    329000.000000  185.250000    4.600000
max    599000.000000  498.000000    5.000000

In [35]:
orders.describe()

,order_date,total_amount_idr,shipping_cost_idr,discount_amount_idr
count,3000,3.000000e+03,3000.000000,3000.000000
mean,2023-11-21 19:12:28.800000,4.981680e+05,23424.824333,12425.351333
min,2022-01-01 00:00:00,1.000000e+03,8076.000000,0.000000
25%,2023-04-08 00:00:00,1.990000e+05,13083.000000,0.000000
50%,2023-12-26 12:00:00,3.990000e+05,22086.000000,0.000000
75%,2024-08-12 00:00:00,6.861738e+05,33177.250000,26430.750000
max,2025-02-28 00:00:00,2.973000e+06,44983.000000,49968.000000
std,NaN,3.883208e+05,10910.022651,16735.649088

In [36]:
order_items.describe()

          quantity  unit_price_idr  subtotal_idr
count  4986.000000     4986.000000  4.986000e+03
mean      1.291617   239158.443642  3.072162e+05
std       0.551826   154642.224566  2.485569e+05
min       1.000000    49000.000000  4.900000e+04
25%       1.000000   119000.000000  1.290000e+05
50%       1.000000   199000.000000  2.380000e+05
75%       1.000000   329000.000000  3.990000e+05
max       3.000000   599000.000000  1.797000e+06

In [37]:
reviews.describe()

            rating                    review_date  helpful_count
count  1500.000000                           1500    1500.000000
mean      4.017333  2023-12-02 03:43:40.800000256       6.964000
min       1.000000            2022-01-06 00:00:00       0.000000
25%       3.000000            2023-04-15 00:00:00       0.000000
50%       4.000000            2024-01-10 00:00:00       2.000000
75%       5.000000            2024-08-19 00:00:00       9.000000
max       5.000000            2025-03-09 00:00:00      50.000000
std       1.128664                            NaN      10.517879

In [38]:
products[products["price_idr"] <= 0]

Empty DataFrame
Columns: [product_id, name, category, sub_category, price_idr, stock, brand, material, avg_rating]
Index: []

In [39]:
#Check numerical columns for impossible values.
print("Invalid Product Prices:")
print(products[products["price_idr"] <= 0])

print("\nNegative Stock:")
print(products[products["stock"] < 0])

print("\nNegative Order Amount:")
print(orders[orders["total_amount_idr"] < 0])

print("\nNegative Shipping Cost:")
print(orders[orders["shipping_cost_idr"] < 0])

print("\nNegative Discount Amount:")
print(orders[orders["discount_amount_idr"] < 0])

print("\nInvalid Quantity:")
print(order_items[order_items["quantity"] <= 0])

print("\nInvalid Ratings:")
print(
    reviews[
        (reviews["rating"] < 1) |
        (reviews["rating"] > 5)
    ]
)

Invalid Product Prices:
Empty DataFrame
Columns: [product_id, name, category, sub_category, price_idr, stock, brand, material, avg_rating]
Index: []

Negative Stock:
Empty DataFrame
Columns: [product_id, name, category, sub_category, price_idr, stock, brand, material, avg_rating]
Index: []

Negative Order Amount:
Empty DataFrame
Columns: [order_id, customer_id, order_date, total_amount_idr, shipping_city, shipping_province, shipping_cost_idr, payment_method, order_status, promo_code, discount_amount_idr, courier]
Index: []

Negative Shipping Cost:
Empty DataFrame
Columns: [order_id, customer_id, order_date, total_amount_idr, shipping_city, shipping_province, shipping_cost_idr, payment_method, order_status, promo_code, discount_amount_idr, courier]
Index: []

Negative Discount Amount:
Empty DataFrame
Columns: [order_id, customer_id, order_date, total_amount_idr, shipping_city, shipping_province, shipping_cost_idr, payment_method, order_status, promo_code, discount_amount_idr, courier]
Index: []

Invalid Quantity:
Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price_idr, subtotal_idr]
Index: []

Invalid Ratings:
Empty DataFrame
Columns: [review_id, order_id, product_id, customer_id, rating, review_text, review_date, helpful_count]
Index: []

In [40]:
#simpler version:
print("Wrong price:", len(products[products["price_idr"] <= 0]))

print("Wrong stock:", len(products[products["stock"] < 0]))

print("Wrong order amount:", len(orders[orders["total_amount_idr"] < 0]))

print("Wrong shipping cost:", len(orders[orders["shipping_cost_idr"] < 0]))

print("Wrong discount:", len(orders[orders["discount_amount_idr"] < 0]))

print("Wrong quantity:", len(order_items[order_items["quantity"] <= 0]))

print(
    "Wrong rating:",
    len(reviews[(reviews["rating"] < 1) | (reviews["rating"] > 5)])
)

Wrong price: 0
Wrong stock: 0
Wrong order amount: 0
Wrong shipping cost: 0
Wrong discount: 0
Wrong quantity: 0
Wrong rating: 0

In [41]:
#2 items × ₹500 = ₹1000 ,  If subtotal_idr says ₹1000, correct If it says ₹900, there is a data problem
order_items["calculated_subtotal"] = (
    order_items["quantity"] * order_items["unit_price_idr"]
)

print(
    "Subtotal mismatches:",
    len(
        order_items[
            order_items["subtotal_idr"] !=
            order_items["calculated_subtotal"]
        ]
    )
)

Subtotal mismatches: 0

In [42]:
#Check categorical values.
print("Product Categories:")
print(products["category"].value_counts())

print("\nOrder Status:")
print(orders["order_status"].value_counts())

print("\nPayment Methods:")
print(orders["payment_method"].value_counts())

print("\nCouriers:")
print(orders["courier"].value_counts())

print("\nGender:")
print(customers["gender"].value_counts())

Product Categories:
category
Dress          30
Jacket         29
Pants          28
Jaket          27
Accessories    26
Aksesoris      26
Celana         24
Kaos           19
dress          18
Kemeja         17
Shirt          16
kemeja         15
T-Shirt        13
kaos           12
Name: count, dtype: int64

Order Status:
order_status
delivered     1776
shipped        445
cancelled      328
processing     300
returned       151
Name: count, dtype: int64

Payment Methods:
payment_method
Transfer Bank    907
GoPay            754
OVO              588
Kartu Kredit     445
QRIS             306
Name: count, dtype: int64

Couriers:
courier
J&T              896
JNE              845
SiCepat          791
Anteraja         307
Pos Indonesia    161
Name: count, dtype: int64

Gender:
gender
Female    451
Male      349
Name: count, dtype: int64

In [43]:
#used strip() to remove extra spaces and title() to standardize text into proper capitalization.
products["category"] = (
    products["category"]
    .str.strip()
    .str.title()
)

In [44]:
products["category"].value_counts()

category
Dress          48
Kemeja         32
Kaos           31
Jacket         29
Pants          28
Jaket          27
Accessories    26
Aksesoris      26
Celana         24
Shirt          16
T-Shirt        13
Name: count, dtype: int64

In [45]:
# Clean customer city and province
customers["city"] = customers["city"].str.strip().str.title()
customers["province"] = customers["province"].str.strip().str.title()

# Clean shipping city and province
orders["shipping_city"] = orders["shipping_city"].str.strip().str.title()
orders["shipping_province"] = orders["shipping_province"].str.strip().str.title()

# Clean order status
orders["order_status"] = orders["order_status"].str.strip().str.lower()

In [47]:
#“I created year, month, month number, and year-month features from the order date for time-based analysis.”
orders["year"] = orders["order_date"].dt.year
orders["month"] = orders["order_date"].dt.month_name()
orders["month_num"] = orders["order_date"].dt.month

#It creates a Year-Month column like 2024-01 from order_date so we can easily analyze monthly trends.
orders["year_month"] = (
    orders["order_date"]
    .dt.to_period("M")
    .astype(str)
)

In [48]:
'''If order is cancelled → is_cancelled = 1, otherwise 0
If order is returned → is_returned = 1, otherwise 0
If order is delivered → is_delivered = 1, otherwise 0
“I created status flag columns using 1 and 0 so I could easily calculate order-status counts and rates.”'''
orders["is_cancelled"] = (orders["order_status"] == "cancelled").astype(int)
orders["is_returned"] = (orders["order_status"] == "returned").astype(int)
orders["is_delivered"] = (orders["order_status"] == "delivered").astype(int)

In [49]:
'''
1 = discount used
0 = no discount
'''
orders["used_discount"] = (
    orders["discount_amount_idr"] > 0
).astype(int)

In [50]:
#Do the final validation.
print(customers.shape)
print(products.shape)
print(orders.shape)
print(order_items.shape)
print(reviews.shape)

(800, 9)
(300, 9)
(3000, 20)
(4986, 7)
(1500, 8)

In [51]:
print(customers.isnull().sum())
print(products.isnull().sum())
print(orders.isnull().sum())
print(order_items.isnull().sum())
print(reviews.isnull().sum())

customer_id          0
name                 0
email                0
phone                0
city                 0
province             0
registration_date    0
gender               0
age_group            0
dtype: int64
product_id      0
name            0
category        0
sub_category    0
price_idr       0
stock           0
brand           0
material        0
avg_rating      0
dtype: int64
order_id               0
customer_id            0
order_date             0
total_amount_idr       0
shipping_city          0
shipping_province      0
shipping_cost_idr      0
payment_method         0
order_status           0
promo_code             0
discount_amount_idr    0
courier                0
year                   0
month                  0
month_num              0
year_month             0
is_cancelled           0
is_returned            0
is_delivered           0
used_discount          0
dtype: int64
item_id                0
order_id               0
product_id             0
quantity               0
unit_price_idr         0
subtotal_idr           0
calculated_subtotal    0
dtype: int64
review_id        0
order_id         0
product_id       0
customer_id      0
rating           0
review_text      0
review_date      0
helpful_count    0
dtype: int64

In [53]:
orders.head() #shows the first 5 rows of the whole orders table.

,order_id,customer_id,order_date,total_amount_idr,shipping_city,shipping_province,shipping_cost_idr,payment_method,order_status,promo_code,discount_amount_idr,courier,year,month,month_num,year_month,is_cancelled,is_returned,is_delivered,used_discount
0,ORD000001,CUST0474,2023-03-23,1951591,Banjarmasin,Kalimantan Selatan,32066,Transfer Bank,shipped,WEEKEND25,44409.0,JNE,2023,March,3,2023-03,0,0,0,1
1,ORD000002,CUST0478,2025-02-26,507000,Palembang,Sumatera Selatan,33769,Kartu Kredit,delivered,No Promo,0.0,JNE,2025,February,2,2025-02,0,0,1,0
2,ORD000003,CUST0306,2022-07-13,199000,Tangerang,Banten,12060,Transfer Bank,delivered,No Promo,0.0,SiCepat,2022,July,7,2022-07,0,0,1,0
3,ORD000004,CUST0777,2024-11-26,119000,Medan,Sumatera Utara,29005,Transfer Bank,cancelled,No Promo,0.0,Anteraja,2024,November,11,2024-11,1,0,0,0
4,ORD000005,CUST0210,2023-07-31,358000,Bandung,Jawa Barat,11192,Kartu Kredit,cancelled,No Promo,0.0,JNE,2023,July,7,2023-07,1,0,0,0

In [56]:
#shows only the important columns you want to verify.
orders[
    [
        "order_id",
        "customer_id",
        "order_date",
        "total_amount_idr",
        "order_status",
        "is_delivered",
        "is_cancelled",
        "used_discount"
    ]
].head()

,order_id,customer_id,order_date,total_amount_idr,order_status,is_delivered,is_cancelled,used_discount
0,ORD000001,CUST0474,2023-03-23,1951591,shipped,0,0,1
1,ORD000002,CUST0478,2025-02-26,507000,delivered,1,0,0
2,ORD000003,CUST0306,2022-07-13,199000,delivered,1,0,0
3,ORD000004,CUST0777,2024-11-26,119000,cancelled,0,1,0
4,ORD000005,CUST0210,2023-07-31,358000,cancelled,0,1,0

In [57]:
orders[
    [
        "order_id",
        "customer_id",
        "order_date",
        "year",
        "month",
        "year_month",
        "total_amount_idr",
        "order_status",
        "is_delivered",
        "is_cancelled",
        "is_returned",
        "used_discount"
    ]
].head()

,order_id,customer_id,order_date,year,month,year_month,total_amount_idr,order_status,is_delivered,is_cancelled,is_returned,used_discount
0,ORD000001,CUST0474,2023-03-23,2023,March,2023-03,1951591,shipped,0,0,0,1
1,ORD000002,CUST0478,2025-02-26,2025,February,2025-02,507000,delivered,1,0,0,0
2,ORD000003,CUST0306,2022-07-13,2022,July,2022-07,199000,delivered,1,0,0,0
3,ORD000004,CUST0777,2024-11-26,2024,November,2024-11,119000,cancelled,0,1,0,0
4,ORD000005,CUST0210,2023-07-31,2023,July,2023-07,358000,cancelled,0,1,0,0

In [58]:
#Save all five cleaned files.
customers.to_csv(
    "customers_clean.csv",
    index=False
)

products.to_csv(
    "products_clean.csv",
    index=False
)

orders.to_csv(
    "orders_clean.csv",
    index=False
)

order_items.to_csv(
    "order_items_clean.csv",
    index=False
)

reviews.to_csv(
    "reviews_clean.csv",
    index=False
)

In [59]:
'''
“I started by understanding the five related datasets and their relationships. I checked data types, missing values, duplicates,
 invalid values, and foreign-key relationships. I cleaned inconsistent categories and text fields, handled missing values based on
 business meaning, validated order calculations, and created useful features such as year, month, cancellation, return, delivery,
 and discount flags. Finally, I exported clean datasets for further analysis.”
 '''

'\n“I started by understanding the five related datasets and their relationships. I checked data types, missing values, duplicates,\n invalid values, and foreign-key relationships. I cleaned inconsistent categories and text fields, handled missing values based on \n business meaning, validated order calculations, and created useful features such as year, month, cancellation, return, delivery, \n and discount flags. Finally, I exported clean datasets for further analysis.”\n '

In [64]:
import os

# Create one folder
os.makedirs("/content/processed", exist_ok=True)

# Save all cleaned files inside it
customers.to_csv("/content/processed/customers_clean.csv", index=False)
products.to_csv("/content/processed/products_clean.csv", index=False)
orders.to_csv("/content/processed/orders_clean.csv", index=False)
order_items.to_csv("/content/processed/order_items_clean.csv", index=False)
reviews.to_csv("/content/processed/reviews_clean.csv", index=False)

In [67]:
import shutil
from google.colab import files

# Zip the processed folder
shutil.make_archive(
    "/content/processed_files",
    "zip",
    "/content/processed"
)

# Download the zip
files.download("/content/processed_files.zip")